#!/usr/bin/env python3
"""Generate the docs index from frontmatter. The index is generated, never hand-written.

Each entry: link | one-line description | read when | status | updated.
Content between the harness markers is replaced; anything outside is preserved.
Works as an Obsidian note too (standard markdown links resolve in Obsidian).

Usage: python3 build_index.py [--project PATH] [--check]
Exit 1 with --check when the index is out of date.
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

from hlib import doc_rel, docs_root, find_project_root, index_path, iter_md, load_config, parse_frontmatter, read_text, rel

START, END = "<!-- harness:index:start -->", "<!-- harness:index:end -->"
HEADER = """---
description: Generated catalog of project knowledge. Read first, then open only what the task needs.
status: active
---
# Index

Generated by `.harness/scripts/build_index.py`. Do not edit between the markers.
"""


def render(root: Path, cfg: dict) -> str:
    ipath = index_path(root, cfg)
    droot = docs_root(root, cfg)
    groups = {}
    for p in sorted(iter_md(droot, exclude=cfg["index"].get("exclude", []))):
        if p.resolve() == ipath.resolve():
            continue
        fm, _ = parse_frontmatter(read_text(p))
        parts = Path(doc_rel(root, cfg, p)).parts
        group = "/".join(parts[:-1]) if len(parts) > 1 else "(root)"
        link = os.path.relpath(p, ipath.parent).replace(os.sep, "/")
        desc = str(fm.get("description", "")).replace("|", "/") or "MISSING DESCRIPTION"
        when = str(fm.get("read_when", "")).replace("|", "/")
        groups.setdefault(group, []).append(
            f"| [{p.stem}]({link.replace(' ', '%20')}) | {desc} | {when} | {fm.get('status', '')} | {fm.get('updated', '')} |")
    lines = [START, ""]
    for g in sorted(groups):
        lines += [f"## {g}", "", "| Doc | What it is | Read when | Status | Updated |", "|---|---|---|---|---|"]
        lines += groups[g] + [""]
    if not groups:
        lines.append("_No documents yet._\n")
    lines.append(END)
    return "\n".join(lines)


def merged(current: str, block: str) -> str:
    if START in current and END in current:
        pre = current.split(START)[0]
        post = current.split(END, 1)[1]
        return pre + block + post
    return HEADER + "\n" + block + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--project", default=".")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    root = find_project_root(Path(a.project))
    cfg = load_config(root)
    path = index_path(root, cfg)
    current = read_text(path) if path.exists() else ""
    new = merged(current, render(root, cfg))
    if a.check:
        if new.strip() != current.strip():
            print(f"index out of date: run python3 .harness/scripts/build_index.py", file=sys.stderr)
            sys.exit(1)
        print("index up to date")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(new if new.endswith("\n") else new + "\n", encoding="utf-8")
    print(f"wrote {rel(root, path)}")


if __name__ == "__main__":
    main()
